name: Build Extension

on:
  push:
    branches:
      - main
      - 'feature/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # - name: Install pnpm
      #   uses: pnpm/action-setup@v2
      #   with:
      #     version: 6.0.2

      - name: Install dependencies
        run: yarn

      - name: Build project
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: yarn build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          path: ./dist
